import { useState, useEffect } from 'react';
import api from '../utils/api';
import { useAuth } from '../context/AuthContext';
import { useToast } from '../context/ToastContext';
import Sidebar from '../components/Sidebar';
import { CheckCircle, Clock, SkipForward, Zap, Plus, Calendar, Filter, X } from 'lucide-react';

const priorityColors = { high: 'var(--danger)', medium: 'var(--warning)', low: 'var(--success)' };

export default function TasksPage() {
  const { user } = useAuth();
  const toast = useToast();
  const [tasks, setTasks] = useState([]);
  const [goals, setGoals] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [showAdd, setShowAdd] = useState(false);
  const [filter, setFilter] = useState('today');
  const [newTask, setNewTask] = useState({ title: '', goalId: '', priority: 'medium', estimatedMinutes: 30 });

  const loadTasks = async () => {
    setLoading(true);
    try {
      const [tasksRes, goalsRes] = await Promise.all([
        filter === 'today' ? api.get('/tasks/today') : api.get(`/tasks?status=${filter}`),
        api.get('/goals'),
      ]);
      setTasks(tasksRes.data.tasks || []);
      setGoals(goalsRes.data.goals || []);
    } catch { toast.error('Failed to load tasks.'); }
    finally { setLoading(false); }
  };

  useEffect(() => { loadTasks(); }, [filter]);

  const generateTasks = async () => {
    setGenerating(true);
    try {
      const { data } = await api.post('/tasks/generate', { hoursAvailable: user?.hoursPerDay || 2 });
      toast.success(`${data.count} tasks generated by AI! 🎯`);
      loadTasks();
    } catch (err) {
      toast.error(err.response?.data?.message || 'Task generation failed.');
    } finally { setGenerating(false); }
  };

  const completeTask = async (id) => {
    try {
      await api.patch(`/tasks/${id}/complete`);
      setTasks((prev) => prev.map((t) => t._id === id ? { ...t, status: 'completed' } : t));
      toast.success('Nice work! ✅');
    } catch (err) { toast.error(err.response?.data?.message || 'Failed to complete task.'); }
  };

  const skipTask = async (id) => {
    try {
      await api.patch(`/tasks/${id}/skip`);
      setTasks((prev) => prev.map((t) => t._id === id ? { ...t, status: 'skipped' } : t));
    } catch { /* silent */ }
  };

  const createTask = async () => {
    if (!newTask.title.trim() || !newTask.goalId) return toast.error('Title and goal are required.');
    try {
      const { data } = await api.post('/tasks', { ...newTask, dueDate: new Date().toISOString() });
      setTasks((prev) => [data.task, ...prev]);
      setNewTask({ title: '', goalId: '', priority: 'medium', estimatedMinutes: 30 });
      setShowAdd(false);
      toast.success('Task added!');
    } catch (err) { toast.error(err.response?.data?.message || 'Failed to create task.'); }
  };

  const pending = tasks.filter((t) => t.status === 'pending');
  const completed = tasks.filter((t) => t.status === 'completed');
  const skipped = tasks.filter((t) => t.status === 'skipped');

  return (
    <div className="app-layout">
      <Sidebar />
      <main className="main-content">
        <div className="topbar">
          <div>
            <h1 className="topbar-title">Tasks</h1>
            <p className="topbar-sub">{pending.length} pending · {completed.length} completed today</p>
          </div>
          <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
            <button className="btn btn-ghost btn-sm" onClick={() => setShowAdd(!showAdd)}><Plus size={15} /> Add Task</button>
            <button className="btn btn-primary btn-sm" onClick={generateTasks} disabled={generating}>
              {generating ? <span className="spinner" style={{ width: 14, height: 14 }} /> : <Zap size={15} />}
              {generating ? 'Generating...' : 'AI Generate'}
            </button>
          </div>
        </div>

        {/* Filter tabs — scrollable on mobile */}
        <div className="filter-tabs-container" style={{ marginBottom: 24 }}>
          <div style={{ display: 'flex', gap: 4, background: 'var(--glass-bg)', border: '1px solid var(--border)', borderRadius: 'var(--radius-md)', padding: 4, width: 'fit-content', minWidth: 'max-content' }}>
            {[['today', 'Today'], ['pending', 'Pending'], ['completed', 'Done'], ['skipped', 'Skipped']].map(([val, label]) => (
              <button key={val} onClick={() => setFilter(val)}
                style={{ padding: '7px 16px', borderRadius: 'calc(var(--radius-md) - 2px)', border: 'none', cursor: 'pointer', fontSize: 13, fontWeight: 600, transition: 'var(--transition)',
                  background: filter === val ? 'var(--gradient)' : 'transparent',
                  color: filter === val ? 'white' : 'var(--text-muted)', whiteSpace: 'nowrap' }}>
                {label}
              </button>
            ))}
          </div>
        </div>

        {/* Add task panel */}
        {showAdd && (
          <div className="card" style={{ padding: 20, marginBottom: 20 }}>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
              <input className="input" placeholder="Task title..." value={newTask.title} onChange={(e) => setNewTask(p => ({ ...p, title: e.target.value }))} />
              <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}>
                <select className="input" style={{ flex: 2, minWidth: 140 }} value={newTask.goalId} onChange={(e) => setNewTask(p => ({ ...p, goalId: e.target.value }))}>
                  <option value="">Select goal...</option>
                  {goals.filter(g => g.status === 'active').map((g) => <option key={g._id} value={g._id}>{g.title}</option>)}
                </select>
                <select className="input" style={{ flex: 1, minWidth: 110 }} value={newTask.priority} onChange={(e) => setNewTask(p => ({ ...p, priority: e.target.value }))}>
                  <option value="high">High</option>
                  <option value="medium">Medium</option>
                  <option value="low">Low</option>
                </select>
                <input type="number" className="input" style={{ width: 100 }} placeholder="Minutes" value={newTask.estimatedMinutes} onChange={(e) => setNewTask(p => ({ ...p, estimatedMinutes: +e.target.value }))} />
              </div>
              <div style={{ display: 'flex', gap: 8 }}>
                <button className="btn btn-primary btn-sm" onClick={createTask} style={{ flex: 1, justifyContent: 'center' }}>Add Task</button>
                <button className="btn btn-ghost btn-icon" onClick={() => setShowAdd(false)}><X size={15} /></button>
              </div>
            </div>
          </div>
        )}

        {loading ? (
          <div style={{ textAlign: 'center', padding: 60 }}><div className="spinner" style={{ width: 36, height: 36, margin: '0 auto' }} /></div>
        ) : tasks.length === 0 ? (
          <div className="card empty-state">
            <div className="empty-icon"><CheckCircle size={28} /></div>
            <div className="empty-title">No tasks here</div>
            <div className="empty-sub">Use AI to generate tasks from your active goals, or add one manually.</div>
            <button className="btn btn-primary btn-sm" onClick={generateTasks} disabled={generating}>
              <Zap size={14} /> Generate with AI
            </button>
          </div>
        ) : (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {tasks.map((task) => (
              <div key={task._id} className={`task-item ${task.status !== 'pending' ? 'completed' : ''}`}
                style={{ borderLeft: `3px solid ${priorityColors[task.priority] || 'var(--border)'}` }}>
                <div onClick={() => task.status === 'pending' && completeTask(task._id)}
                  className={`task-check ${task.status === 'completed' ? 'checked' : ''}`}
                  style={{ cursor: task.status === 'pending' ? 'pointer' : 'default' }}>
                  {task.status === 'completed' && <CheckCircle size={12} color="white" />}
                  {task.status === 'skipped' && <SkipForward size={12} color="var(--text-muted)" />}
                </div>

                <div style={{ flex: 1, minWidth: 0 }}>
                  <div className="task-title" style={{ marginBottom: 2 }}>{task.title}</div>
                  {task.goalId?.title && <div style={{ fontSize: 11, color: 'var(--text-muted)' }}>{task.goalId.title}</div>}
                </div>

                <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                  {task.estimatedMinutes && <span className="task-time"><Clock size={12} />{task.estimatedMinutes}m</span>}
                  {task.isAiGenerated && <span className="badge badge-indigo" style={{ fontSize: 10 }}><Zap size={9} /> AI</span>}
                  {task.status === 'pending' && (
                    <button onClick={() => skipTask(task._id)} className="btn btn-ghost btn-sm" style={{ padding: '4px 10px', fontSize: 12 }}>
                      <SkipForward size={12} /> Skip
                    </button>
                  )}
                </div>
              </div>
            ))}
          </div>
        )}
      </main>
    </div>
  );
}
