const mongoose = require('mongoose');

const nudgeSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'User ID is required'],
      index: true,
    },
    goalId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Goal',
      required: [true, 'Goal ID is required'],
    },
    type: {
      type: String,
      enum: {
        values: ['warning', 'suggestion', 'encouragement'],
        message: 'Nudge type must be one of: warning, suggestion, encouragement',
      },
      required: [true, 'Nudge type is required'],
    },
    message: {
      type: String,
      required: [true, 'Nudge message is required'],
      trim: true,
      maxlength: [500, 'Nudge message cannot exceed 500 characters'],
    },
    isRead: {
      type: Boolean,
      default: false,
    },
    readAt: {
      type: Date,
      default: null,
    },
    isDismissed: {
      type: Boolean,
      default: false,
    },
    dismissedAt: {
      type: Date,
      default: null,
    },
    // Optional step breakdown if Gemini suggests breaking a step into smaller pieces
    optionalStepBreakdown: {
      type: [String],
      default: [],
    },
    // Was this nudge generated by the adaptation engine or something else?
    source: {
      type: String,
      enum: ['adaptation_engine', 'system'],
      default: 'adaptation_engine',
    },
  },
  {
    timestamps: true,
  }
);

// Efficient lookup for unread/undismissed nudges per user
nudgeSchema.index({ userId: 1, isRead: 1, isDismissed: 1, createdAt: -1 });
nudgeSchema.index({ userId: 1, goalId: 1, createdAt: -1 });

module.exports = mongoose.model('Nudge', nudgeSchema);
